### ISSUE TITLE
ARC?

### ISSUE THREAD

**Issue by gerchicov-bp** [Raizlabs/RZViewActions#10]
Your code is written for ARC but doesn't check it. In my case it caused problems when I tried to use it via copy-paste in MRR project. I suggest one of the following things:
- to add some code for MRR;
- to add an assertion if a programmer wants to use your code as MRR.

**Comment by jvisenti** [comment]
This library is ARC only, and will not support MRR. However, it shouldn't be too much work to add support in a fork. Happy to look at a PR, but closing this issue until then
