### ISSUE TITLE
Springy animation?

### ISSUE THREAD

**Issue by x4080** [Raizlabs/RZViewActions#16]
Hi, can springy animation work with this cool library ?
Little question not an issue actually :)

**Comment by jvisenti** [comment]
@x4080 There is support for this via

```
+ (RZViewAction *)springAction:(RZViewActionBlock)action 
                   withDamping:(CGFloat)dampingRatio
               initialVelocity:(CGFloat)velocity
                       options:(UIViewAnimationOptions)options
                      duration:(NSTimeInterval)duration;
```

If this method isn't working for you please let me know!

**Comment by x4080** [comment]
Thanks @jvisenti

**Comment by jvisenti** [comment]
Sure thing. Closing this until something else comes up regarding springy animations
