### ISSUE TITLE
Trouble with @import UIKit;

### ISSUE THREAD

**Issue by gerchicov-bp** [Raizlabs/RZViewActions#6]
Does it have any special purpose? The problem is described by someone here:
http://stackoverflow.com/questions/25883153/cant-import-embedded-framework-with-xcode-6-gm
But the project is not my own and I can't simply delete all the submodules and in the same time I must edit your library to replace `@import UIKit;` -> `#import <UIKit/UIKit.h>`.
Could you fix this issue?

**Comment by ZevEisenberg** [comment]
Can you enable module support in build settings?

**Comment by gerchicov-bp** [comment]
I forgot to mention: a lot of people work on this project so yes, I can't simply change the project settings each time I want.

**Comment by ZevEisenberg** [comment]
If we just change it, projects with a certain warning flag will get warnings that we _don’t_ use `@import`. But I believe there’s an “are modules enabled?” macro that would allow us to conditionally use `@import` or `#import` depending on the host project. I’m on my phone and can’t find it just at the moment.

**Comment by jvisenti** [comment]
@ZevEisenberg I'd rather have the warning than the `@import`. We generally try to use `#import` in our open source code, but this one must have slipped through. Any objection to simply changing to `#import`? I was unable to find a macro to conditionally use the module import.

**Comment by ZevEisenberg** [comment]
@jvisenti try `__has_feature(modules)`. Might want to make that the new best practice, although code without modules enabled is only going to get scarcer.

**Comment by jvisenti** [comment]
This should be fixed in version 0.2.1
